wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1682109368.559262
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
epoch:
  desc: null
  value: 50
learing_rate:
  desc: null
  value: 0.005
